version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: example_batch_db
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_DB: 'products'
      POSTGRES_USER: 'laboratory'
      POSTGRES_PASSWORD: '1q2w3e4r'
    ports:
      - '5432:5432'
  wiremock:
    container_name: wiremock
    image: rodolpheche/wiremock
    ports:
      - "9001:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: --verbose
    networks:
      - batch-network

networks:
  batch-network: